EcommerceWebsite_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("account_app.urls")),
    path("", include("home_app.urls")),
    path("products/", include("product_app.urls")),
    path("cart/", include("cart_app.urls")),
    path("blog/", include("weblog_app.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account_app/urls.py
from django.urls import path
from . import views


app_name = "accounts_app"
urlpatterns = [
    path("register", views.register_page, name="register_page"),
    path("edit", views.edit_page, name="edit_page"),
    path("logout", views.logout_page, name="logout_page"),
    path("login/", views.login_page, name="login_page"),
    path("checkotp", views.otpcheck, name="check_otp"),
    path("passchange", views.change_password, name="pass_change"),
    path("passchangepage", views.change_password_page, name="pass_change_page"),
    path("confirm_code", views.confirm_code, name="confirm_code"),
    path("after_confirm", views.after_confirm, name="after_confirm"),
    path("user_panel", views.profile_page, name="user_panel"),
]

cart_app/urls.py
from django.urls import path
from . import views

app_name = "cart_app"
urlpatterns = [
    path("cart_add/<int:pk>/", views.cart_add, name="add"),
    path("cart_add_store/<int:pk>/", views.cart_add_store, name="cart_add_store"),
    path("remove_from_cart/<int:pk>/", views.remove_from_cart, name="remove_cart"),
    path("cart_list", views.cart_page, name="cart_list"),
    path("cart_update/<int:pk>", views.cart_update, name="cart_update"),
    path("checkout", views.checkout, name="checkout"),
    path("order_creation", views.order_creation, name="order_creation"),
    path("order_detail/<int:pk>", views.order_detail, name="order_detail"),
    path("factor_page/<int:pk>", views.view_factor, name="factor_page"),
    path("purchases", views.purchases, name="purchases"),
    path("address", views.address, name="address"),
    path("edit_address/<int:pk>", views.edit_address, name="edit_address"),
    path("test", views.test1),
]

home_app/urls.py
from django.urls import path
from . import views


app_name = "home_app"
urlpatterns = [
    path("", views.home_app, name="main"),
    path("about_us", views.about_us, name="about_us"),
    path("contact_us", views.contact_us, name="contant_us"),
]

account_app/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.utils import timezone


class MyUserManager(BaseUserManager):
    def create_user(self, phone=None, password=None, username=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not phone:
            raise ValueError("Users must have an Phone Number")

        user = self.model(
            phone=phone,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, phone, password, email=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            phone,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    username = models.CharField(max_length=50)
    phone = models.CharField(max_length=11, unique=True, null=True, blank=True)
    full_name = models.CharField(max_length=100, null=True, blank=True)
    prof_pic = models.ImageField(upload_to="img/prof_pics", null=True, blank=True)
    password = models.CharField(max_length=100)
    email = models.EmailField(
        verbose_name="email address",
        max_length=255,
        null=True, blank=True
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = "phone"
    REQUIRED_FIELDS = ["email"]

    def __str__(self):
        return self.phone

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


class OTP(models.Model):
    token = models.CharField(max_length=200, null=True, blank=True)
    phone = models.CharField(max_length=11, unique=True)
    password = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(unique=True, blank=True, null=True)
    code = models.SmallIntegerField(null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now, null=True, blank=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        expired_otp_code = OTP.objects.filter(created_at__lt=timezone.now() - timezone.timedelta(seconds=20))
        expired_otp_code.delete()

    def __str__(self):
        return self.phone


class ForgotenPassword(models.Model):
    phone = models.CharField(max_length=11, unique=True)
    token = models.CharField(max_length=200, null=True, blank=True, unique=True)
    code = models.SmallIntegerField(null=True, blank=True)

    def __str__(self):
        return self.phone

account_app/forms.py
from django import forms
from django.core import validators
from django.core.validators import ValidationError


def start_with_0(value):
    if value[0] != "0":
        raise forms.ValidationError("phone should start with 0")


def eleven_numbers(value):
    if len(value) != 11:
        raise forms.ValidationError("شماره تماس باید 11 رقم باشد!")


class LoginForm(forms.Form):
    phone = forms.CharField(widget=forms.TextInput(attrs={"class": 'form-control py-4'}), validators=[start_with_0,
                                                                                                      eleven_numbers])
    password = forms.CharField(widget=forms.PasswordInput(attrs={"class": 'form-control py-4'}))


class OtpLoginForm(forms.Form):
    phone = forms.CharField(widget=forms.TextInput(attrs={"placeholder": '09xxxxxxxxx', 'class': 'form-control py-4'}),
                            validators=[start_with_0, eleven_numbers])


class CheckOtpForm(forms.Form):
    code = forms.CharField(
        widget=forms.TextInput(attrs={'class': "form-control text-center py-4", 'placeholder': 'کد را وارد کنید'}),
        validators=[validators.MaxLengthValidator(4)])

account_app/views.py
import random
from datetime import datetime, timedelta
from uuid import uuid4

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import get_user_model

from cart_app.models import OrderItem
from .models import User, OTP, ForgotenPassword
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from . import forms
from random import randint
# import ghasedakpack
from django.utils import timezone
from django.core.mail import send_mail


# User = get_user_model()
# sms = ghasedakpack.Ghasedak('71287bb24809cba0c9fc00e3697305b0ad3272bfe1b7d7946eb92c560931fc99')  # Api key code


# Create your views here.


def login_page(request):
    if request.user.is_authenticated:
        return redirect("home_app:main")

    if request.method == "POST":
        form = forms.LoginForm(request.POST)
        next_page = request.GET.get("next")
        if form.is_valid():
            cd = form.cleaned_data
            phone = cd['phone']
            password = cd['password']

            user = authenticate(username=phone, password=password)
            if user is not None:
                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                messages.info(request, f"You are now logged in as {phone}.")
            else:
                form = forms.LoginForm(request.POST)
                error = 'شماره تلفن یا رمز عبور شما اشتباه است!'
                return render(request, "account_app/login.html", context={"form": form, "error": error})
            if next_page:
                return redirect(next_page)
            return redirect("home_app:main")
    else:
        form = forms.LoginForm()
    return render(request, "account_app/login.html", context={"form": form})


@login_required
def edit_page(request):
    if request.user.is_authenticated is None:
        return redirect("accounts_app:register_page")

    if request.method == "POST":
        username = request.POST.get("username")
        password1 = request.POST.get("pass1")
        password2 = request.POST.get("pass1")
        profile_picture = request.FILES.get("prof_pic")
        fullname = request.POST.get("fullname")
        email = request.POST.get("email")
        phone = request.POST.get("phone")
        user = request.user

        if username:
            user.username = username
        else:
            user.username = request.user.username

        user.prof_pic = profile_picture
        user.full_name = fullname
        user.email = email
        if password1 and password2:
            if password1 == password2:
                user.set_password(password1)
            else:
                user.set_password(request.user.password)
        user.save()
        user = authenticate(username=phone, password=password1)
        login(request, user)
        return redirect("home_app:main")
    return render(request, "account_app/edit_profile.html")


@login_required
def change_password_page(request):
    if request.method == "POST":
        randcode = randint(1000, 9999)
        token = str(uuid4())
        phone = request.POST.get("phone")
        print(randcode)
        new_password = ForgotenPassword.objects.create(phone=phone, token=token, code=randcode)
        return redirect(reverse("accounts_app:confirm_code") + f"?token={token}")
    return render(request, "account_app/passwordchange.html")


def confirm_code(request):
    code = forms.CheckOtpForm(request.POST)
    if request.method == "POST":
        code = forms.CheckOtpForm(request.POST)

        if code.is_valid():
            cd = code.cleaned_data
            token = request.GET.get("token")
            if ForgotenPassword.objects.filter(code=cd['code'], token=token).exists():
                user_phone = ForgotenPassword.objects.get(token=token)  # First we will get the phone number of the user
                new_password = randint(1000, 9999)  # Second we create the new password!
                print("Your new password:", new_password)

                user = User.objects.get(phone=user_phone.phone)  # Third we get the user
                user.set_password(str(new_password))  # Forth we change the password
                user.save()  # Fivth we save the operation

                user_phone.delete()

                return redirect("accounts_app:after_confirm")
    return render(request, "account_app/confirmcode.html", context={"code": code})


def after_confirm(request):
    return render(request, "account_app/AfterConfirm.html")


@login_required
def change_password(request):
    if request.user.is_authenticated:
        return redirect("home_app:main")

    if request.method == "POST":
        user = request.user
        newpass = random.randint(1000, 9999)
        subject = 'Password Change!'
        message = f"This is your new password = {newpass}"
        from_email = 'samalizadeh899@gmail.com'
        recipient_list = [user.email]
        user.set_password(str(newpass))
        user.save()
        send_mail(subject, message, from_email, recipient_list)
        return HttpResponse("Your password has been sent to your email and changed!")


@login_required
def logout_page(request):
    logout(request)
    return redirect("home_app:main")


def register_page(request):
    if request.user.is_authenticated:
        return redirect("home_app:main")

    if request.method == "GET":
        form = forms.OtpLoginForm()
        return render(request, "account_app/register.html", {"form": form})

    if request.method == "POST":
        form = forms.OtpLoginForm(request.POST)
        if form.is_valid():
            randcode = randint(1000, 9999)
            cd = form.cleaned_data
            token = str(uuid4())
            password1 = request.POST.get("pass")
            password2 = request.POST.get("repass")
            email = request.POST.get("email")

            if password1 == password2:  # Checking passwords
                email_check = User.objects.filter(email=email).exists()
                if email_check:
                    error = "This email exist`s !"  # Checking email
                    return render(request, "account_app/register.html", context={"errors": error, "form": form})
                else:
                    phone = User.objects.filter(phone=cd['phone']).exists()
                    if phone:
                        error = "This Phone number exist`s !"  # Checking the phonenumber
                        return render(request, "account_app/register.html", context={"errors": error, "form": form})
                    else:
                        OTP.objects.create(phone=cd['phone'], code=randcode, token=token, password=password1,
                                           email=email)
                        print(randcode)  # And the last one , sending code to register the user!
                        return redirect(reverse("accounts_app:check_otp") + f"?token={token}")
            else:
                error = "Passwords are not same !"
                return render(request, "account_app/register.html", context={"errors": error})
            # sms.verification(
            #     {'receptor': cd["phone"], 'type': '1', 'template': 'websitecode', 'param1': randcode})
        else:
            form.add_error("phone", "invalid data")
        return render(request, "account_app/register.html", context={"form": form})


def otpcheck(request):
    if request.method == "GET":
        form = forms.CheckOtpForm()
        return render(request, "account_app/checkotp.html", {"form": form})

    if request.method == "POST":
        token = request.GET.get("token")
        form = forms.CheckOtpForm(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            if OTP.objects.filter(code=cd['code'], token=token).exists():
                otp = OTP.objects.get(token=token)  # For getting the password from otp model!
                user = User.objects.create(phone=otp.phone, email=otp.email)

                password = otp.password
                user.set_password(password)
                user.save()

                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                otp.delete()
                return redirect("home_app:main")
            else:
                print("hello 1")
        else:
            print("hello 2")
            form.add_error("code", "invalid data")

        return render(request, "account_app/checkotp.html", {"form": form})


@login_required
def profile_page(request):
    latest_pruchases = OrderItem.objects.filter(order__user=request.user).order_by("-order__created_at")[:3]
    return render(request, "account_app/user-panel.html", context={"latest_purchases": latest_pruchases})

account_app/templates/account_app/AfterConfirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>After confirm code</title>
</head>
<body>
        <p style="font-size: xx-large; font-weight: bold">پسورد شما با موفقیت تغییر یافت !</p>
        <a href="{% url "accounts_app:login_page" %}">رفتن به صفحه لاگین</a>
</body>
</html>

account_app/templates/account_app/edit_profile.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <div class="content">
        <div class="container-fluid">

            <!-- start side-menu in mobile -->
            <div class="custom-filter d-lg-none d-block">
                <button class="btn btn-filter-float border-0 main-color-two-bg shadow-box px-4 rounded-3 position-fixed"
                        style="z-index: 999;bottom:80px;" type="button" data-bs-toggle="offcanvas"
                        data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">
                    <i class="bi bi-list font-20 fw-bold text-white"></i>
                    <span class="d-block font-14 text-white">منو</span>
                </button>

                <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasRight"
                     aria-labelledby="offcanvasRightLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="offcanvasRightLabel">منو</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <div class="panel-side">
                            <div class="content-box pb-0">
                                <div class="container-fluid">
                                    <div class="panel-box">
                                        <div class="d-flex align-items-center">
                                            {% if request.user.prof_pic %}
                                                <img src="{{ request.user.prof_pic.url }}"
                                                     class="img-fluid img-profile-panel rounded-circle me-3 shadow-md"
                                                     alt="">
                                            {% else %}
                                                <img src="{% static "image/user.png" %}"
                                                     class="img-fluid img-profile-panel rounded-circle me-3 shadow-md"
                                                     alt="">
                                            {% endif %}
                                            <div class="d-grid gap-2">
                                                <h6 class="font-14 main-color-one-color">حساب کاربری من</h6>
                                                <h6 class="font-14">{{ request.user.full_name }}</h6>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="profile-box">
                                        <nav class="navbar profile-box-nav">
                                            <ul class="navbar-nav flex-column">
                                                <li class="nav-item active"><a href="" class="nav-link">
                                                    <i class="bi bi-house-door"></i>پروفایل</a>
                                                </li>
                                                <li class="nav-item"><a href="" class="nav-link">
                                                    <i class="bi bi-cart-check"></i>سفارش های من <span
                                                        class="badge rounded-pill badge-spn">{{ user_purchase|length }}</span></a>
                                                </li>
                                                <li class="nav-item"><a href="" class="nav-link">
                                                    <i class="bi bi-pin-map"></i>آدرس های من</a>
                                                </li>
                                                <li class="nav-item"><a href="" class="nav-link">
                                                    <i class="bi bi-bell"></i>پیام ها و اطلاعیه ها</a>
                                                </li>
                                                <li class="nav-item"><a href="" class="nav-link">
                                                    <i class="bi bi-chat-dots"></i>نظرات من</a>
                                                </li>
                                                <li class="nav-item"><a href="" class="nav-link">
                                                    <i class="bi bi-question-circle"></i>درخواست پشتیبانی</a>
                                                </li>
                                                <li class="nav-item"><a href="" class="nav-link">
                                                    <i class="bi bi-heart"></i>محصولات مورد علاقه</a>
                                                </li>
                                                <li class="nav-item"><a href="" class="nav-link">
                                                    <i class="bi bi-gift"></i>کد های تخفیف من</a>
                                                </li>
                                                <li class="nav-item"><a href="{% url "accounts_app:logout_page" %}"
                                                                        class="nav-link">
                                                    <i class="bi bi-arrow-right-square"></i>خروج از حساب کاربری</a>
                                                </li>
                                            </ul>
                                        </nav>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- end side-menu in mobile -->

            <div class="dashboard-panel">
                <div class="row gy-3">
                    {% include "includes/admin_panel_include.html" %}
                    <div class="col-lg-9">
                        <div class="content-box">
                            <div class="container-fluid">
                                <form action="{% url "accounts_app:edit_page" %}" method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="form-group title-panel">
                                        <h6 class="font-16">
                                            ویرایش اطلاعات کاربری
                                        </h6>
                                    </div>
                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-floating mb-3">
                                                    <input type="text" name="fullname" value="{{ request.user.full_name }}" class="form-control float-input"
                                                           id="floatingInputFname"
                                                           placeholder="نام و نام خانوادگی خود را وارد کنید">
                                                    <label for="floatingInputFname">نام و نام خانوادگی خود را وارد
                                                        کنید</label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {#                                    <div class="form-floating mb-3">#}
                                    {#                                        <input type="text" class="form-control float-input" id="floatingInputStreet"#}
                                    {#                                               placeholder="آدرس">#}
                                    {#                                        <label for="floatingInputStreet">آدرس</label>#}
                                    {#                                    </div>#}
                                    <div class="form-floating mb-3">
                                        <input type="text" name="username" value="{{ request.user.username }}" class="form-control float-input"
                                               id="floatingInputMobile"
                                               placeholder="نام کاربری">
                                        <label for="floatingInputMobile">نام کاربری</label>
                                    </div>
                                    <div class="form-floating mb-3">
                                        <input type="text" name="email" value="{{ request.user.email }}" class="form-control float-input"
                                               id="floatingInputEmail"
                                               placeholder="ایمیل">
                                        <label for="floatingInputEmail">ایمیل</label>
                                    </div>
                                    <input type="hidden" name="phone" value="{{ request.user.phone }}">
                                    <div class="form-floating mb-3">
                                        <input type="file" name="prof_pic" class="form-control float-input"
                                               id="floatingInputEmail"
                                               placeholder="عکس پروفایل">
                                        <label for="floatingInputEmail">آواتار</label>
                                    </div>
                                    <div class="form-floating mb-3">
                                        <input type="password" name="pass1" class="form-control float-input"
                                               id="floatingInputEmail"
                                               placeholder="گذرواژه">
                                        <label for="floatingInputEmail">گذرواژه</label>
                                    </div>
                                    <div class="form-floating mb-3">
                                        <input type="password" name="pass2" class="form-control float-input"
                                               id="floatingInputEmail"
                                               placeholder="تکرار گذرواژه">
                                        <label for="floatingInputEmail">تکرار گذرواژه</label>
                                    </div>
                                    <div class="mb-2">
                                        <button type="submit"
                                                class="btn border-0 main-color-one-bg waves-effect waves-light py-2 px-5">
                                            <i class="bi bi-pencil-square text-white me-1"></i> ویرایش
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}