EcommerceWebsite_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("account_app.urls")),
    path("", include("home_app.urls")),
    path("products/", include("product_app.urls")),
    path("cart/", include("cart_app.urls")),
    path("blog/", include("weblog_app.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account_app/urls.py
from django.urls import path
from . import views


app_name = "accounts_app"
urlpatterns = [
    path("register", views.register_page, name="register_page"),
    path("edit", views.edit_page, name="edit_page"),
    path("logout", views.logout_page, name="logout_page"),
    path("login/", views.login_page, name="login_page"),
    path("checkotp", views.otpcheck, name="check_otp"),
    path("passchange", views.change_password, name="pass_change"),
    path("passchangepage", views.change_password_page, name="pass_change_page"),
    path("confirm_code", views.confirm_code, name="confirm_code"),
    path("after_confirm", views.after_confirm, name="after_confirm"),
    path("user_panel", views.profile_page, name="user_panel"),
]

cart_app/urls.py
from django.urls import path
from . import views

app_name = "cart_app"
urlpatterns = [
    path("cart_add/<int:pk>/", views.cart_add, name="add"),
    path("cart_add_store/<int:pk>/", views.cart_add_store, name="cart_add_store"),
    path("remove_from_cart/<int:pk>/", views.remove_from_cart, name="remove_cart"),
    path("cart_list", views.cart_page, name="cart_list"),
    path("cart_update/<int:pk>", views.cart_update, name="cart_update"),
    path("checkout", views.checkout, name="checkout"),
    path("order_creation", views.order_creation, name="order_creation"),
    path("order_detail/<int:pk>", views.order_detail, name="order_detail"),
    path("factor_page/<int:pk>", views.view_factor, name="factor_page"),
    path("purchases", views.purchases, name="purchases"),
    path("address", views.address, name="address"),
    path("edit_address/<int:pk>", views.edit_address, name="edit_address"),
    path("test", views.test1),
]

product_app/urls.py
from django.urls import path
from . import views

app_name = "product_app"
urlpatterns = [
    path("detail/<str:slug>", views.product_detail, name="detail"),
    path("add_review/<int:pk>", views.add_comment, name="add_review"),
    path("del_review/<int:pk>", views.del_comments, name="del_review"),
    path("store", views.store, name="store"),
    path("user_comments", views.user_comments, name="user_comments"),
    path("like/<str:slug>/<int:pk>/", views.like, name="like"),
    path("un_like/<str:slug>", views.un_like, name="unlike"),
    path("wishlist", views.wishlist, name="wishlist"),

]

templates/includes/admin_panel_include.html
{% load static %}
<div class="col-lg-3 d-lg-block d-none">
    <div class="panel-side">
        <div class="content-box pb-0">
            <div class="container-fluid">
                <div class="panel-box">
                    <div class="d-flex align-items-center">
                        {% if request.user.prof_pic %}
                            <img src="{{ request.user.prof_pic.url }}"
                                 class="img-fluid img-profile-panel rounded-circle me-3 shadow-md"
                                 alt="">
                        {% else %}
                            <img src="{% static "image/user.png" %}"
                                 class="img-fluid img-profile-panel rounded-circle me-3 shadow-md"
                                 alt="">
                        {% endif %}
                        <div class="d-grid gap-2">
                            <h6 class="font-14 main-color-one-color">حساب کاربری من</h6>
                            <h6 class="font-14">{{ request.user.full_name }}</h6>
                        </div>
                    </div>
                </div>
                <div class="profile-box">
                    <nav class="navbar profile-box-nav">
                        <ul class="navbar-nav flex-column">
                            <li class="nav-item {% if request.resolver_match.url_name == "user_panel" %}active{% endif %}">
                                <a href="{% url "accounts_app:user_panel" %}" class="nav-link">
                                    <i class="bi bi-house-door"></i>پروفایل</a>
                            </li>
                            <li class="nav-item {% if request.resolver_match.url_name == "purchases" %}active{% endif %}">
                                <a href="{% url "cart_app:purchases" %}" class="nav-link">
                                    <i class="bi bi-cart-check"></i>سفارش های من <span
                                        class="badge rounded-pill badge-spn">{{ user_purchase|length }}</span></a>
                            </li>
                            <li class="nav-item {% if request.resolver_match.url_name == "address" %}active{% endif %}">
                                <a href="{% url "cart_app:address" %}" class="nav-link">
                                    <i class="bi bi-pin-map"></i>آدرس های من<span
                                        class="badge rounded-pill badge-spn">{{ address_len }}</span></a>
                            </li>
                            <li class="nav-item"><a href="" class="nav-link">
                                <i class="bi bi-bell"></i>پیام ها و اطلاعیه ها</a>
                            </li>
                            <li class="nav-item {% if request.resolver_match.url_name == "user_comments" %}active{% endif %}">
                                <a href="{% url "product_app:user_comments" %}" class="nav-link">
                                    <i class="bi bi-chat-dots"></i>نظرات من</a>
                            </li>
                            <li class="nav-item"><a href="" class="nav-link">
                                <i class="bi bi-question-circle"></i>درخواست پشتیبانی</a>
                            </li>
                            <li class="nav-item {% if request.resolver_match.url_name == "wishlist" %}active{% endif %}">
                                <a href="{% url "product_app:wishlist" %}" class="nav-link">
                                    <i class="bi bi-heart"></i> محصولات مورد علاقه<span
                                        class="badge rounded-pill badge-spn">{{ len_likee }}</span></a>
                            </li>
                            <li class="nav-item"><a href="" class="nav-link">
                                <i class="bi bi-gift"></i>کد های تخفیف من</a>
                            </li>
                            <li class="nav-item"><a href="{% url "accounts_app:logout_page" %}"
                                                    class="nav-link">
                                <i class="bi bi-arrow-right-square"></i>خروج از حساب کاربری</a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>

templates/includes/cart_template.html
{% load static %}
{% for item in cart.cart_items.all %}
    <div class="item">
        <div class="row gy-2">
            <div class="col-4">
                <div class="image">
                    <img src="{{ item.product.image.url }}" alt="" class="img-fluid">
                </div>
            </div>
            <div class="col-8">
                <div class="title">
                    <h6 class="font-14"><a
                            href="{% url "product_app:detail" item.product.id %}">{{ item.product.title }}</a>
                    </h6>
                    <p class="mb-0 text-muted font-12 mt-2">مدل {{ item.product.title }}</p>
                    <p class="mb-0 text-muted font-12 mt-2">رنگ {{ item.color }}</p>
                </div>
                <div class="price">
                    <p class="text-end mb-2 price-off fw-bold">{{ item.total_price }} تومان</p>
                    <p class="text">{{ item.quantity }}x</p>
                </div>
                <div class="action d-flex justify-content-between align-items-center">
                    <div class="remove bg-light  rounded-3">
                        <a onclick="remove_from_cart({{ item.id }})">
                            <i class="bi bi-x font-25"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% empty %}
    <a href="{% url "product_app:store" %}">سبد خرید شما خالی است !</a>
{% endfor %}
{% if cart.cart_items.all %}
    <div class="item">
        <div class="factor">
            <div class="title">
                <div class="d-flex align-items-center">
                    <img src="{% static "image/shopping-bag.png" %}" class="img-fluid" alt="">
                    <h6 class="font-16">سفارش شما</h6>
                </div>
            </div>
            <div class="d-flex mb-3 align-items-center justify-content-between">
                <p class="fw-bold mb-0">محصول</p>
                <p class="fw-bold mb-0">قیمت کل</p>
            </div>
            {% for item in cart.cart_items.all %}
                <div
                        class="factor-item p-2 rounded-3 shadow-sm bg-light d-flex align-items-center justify-content-between">
                    <p class="mb-0">{{ item.product.title }}</p>{{ item.quantity }}x
                    <p class="mb-0">{{ item.price }} تومان</p>
                </div>
            {% endfor %}
            <div
                    class="factor-item p-2 rounded-3 shadow-sm bg-light d-flex align-items-center justify-content-between">
                <p class="mb-0 fw-bold">جمع کل:</p>
                <p class="mb-0">{{ cart.subtotal }} تومان</p>
            </div>
            <div class="action mt-3 d-flex align-items-center justify-content-center">
                <a href="{% url "cart_app:cart_list" %}"
                   class="btn border-0 main-color-two-bg rounded-3">سبد خرید</a>
                <a href="{% url "cart_app:checkout" %}"
                   class="btn border-0 main-color-one-bg rounded-3 ms-2">تسویه حساب</a>
            </div>
        </div>
    </div>
{% endif %}