EcommerceWebsite_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("account_app.urls")),
    path("", include("home_app.urls")),
    path("products/", include("product_app.urls")),
    path("cart/", include("cart_app.urls")),
    path("blog/", include("weblog_app.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart_app/urls.py
from django.urls import path
from . import views

app_name = "cart_app"
urlpatterns = [
    path("cart_add/<int:pk>/", views.cart_add, name="add"),
    path("cart_add_store/<int:pk>/", views.cart_add_store, name="cart_add_store"),
    path("remove_from_cart/<int:pk>/", views.remove_from_cart, name="remove_cart"),
    path("cart_list", views.cart_page, name="cart_list"),
    path("cart_update/<int:pk>", views.cart_update, name="cart_update"),
    path("checkout", views.checkout, name="checkout"),
    path("order_creation", views.order_creation, name="order_creation"),
    path("order_detail/<int:pk>", views.order_detail, name="order_detail"),
    path("factor_page/<int:pk>", views.view_factor, name="factor_page"),
    path("purchases", views.purchases, name="purchases"),
    path("address", views.address, name="address"),
    path("edit_address/<int:pk>", views.edit_address, name="edit_address"),
    path("test", views.test1),
]

home_app/urls.py
from django.urls import path
from . import views


app_name = "home_app"
urlpatterns = [
    path("", views.home_app, name="main"),
    path("about_us", views.about_us, name="about_us"),
    path("contact_us", views.contact_us, name="contant_us"),
]

cart_app/models.py
from django.db import models
from account_app.models import User
from product_app.models import Product


# Create your models here.


class Cart(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE, related_name="user_cart")

    def __str__(self):
        if self.user:
            return self.user.phone

    # how many products are in the basket
    def len(self):
        return self.cart_items.count()

    def subtotal(self):
        subtotal = 0
        for item in self.cart_items.all():
            subtotal += item.total_price()
        return subtotal

    def total_quantity(self):
        total = 0
        for item in self.cart_items.all():
            total += item.quantity
        return total


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name="cart_items")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="cart_items")
    color = models.CharField(max_length=75)
    quantity = models.PositiveSmallIntegerField(default=0)
    price = models.FloatField(null=True, blank=True)

    def total_price(self):
        if self.quantity and self.price:
            price = self.quantity * self.price
            return price
        else:
            return 0


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="addresses")
    fname = models.CharField(max_length=50)
    lname = models.CharField(max_length=50, null=True, blank=True)
    email = models.EmailField(blank=True, null=True)
    phone = models.CharField(max_length=11)
    address = models.TextField()
    state = models.CharField(max_length=30, null=True, blank=True)
    city = models.CharField(max_length=40, null=True, blank=True)
    postal_code = models.CharField(max_length=20)

    def __str__(self):
        return self.user.phone


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="orders")
    f_name = models.CharField(max_length=50, null=True, blank=True)
    l_name = models.CharField(max_length=50, null=True, blank=True)
    state = models.CharField(max_length=20, null=True, blank=True)
    city = models.CharField(max_length=30, null=True, blank=True)
    phone_number = models.CharField(max_length=11, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    postal_code = models.CharField(max_length=15, null=True, blank=True)
    optional_notes = models.TextField(null=True, blank=True)
    total_price = models.IntegerField(default=0)
    is_paid = models.BooleanField(default=False, null=True, blank=True)
    order_number = models.CharField(max_length=16, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    address = models.TextField()

    def __str__(self):
        return self.user.phone


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="items")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="items")
    color = models.CharField(max_length=30)
    quantity = models.IntegerField(default=1)
    price = models.PositiveIntegerField()

    @property
    def costprice(self):
        return self.quantity * self.price

    def __str__(self):
        return f"{self.order.user.username} - {self.product.title}"

cart_app/views.py
import random
from datetime import datetime

from persiantools.jdatetime import JalaliDate

from product_app.models import Product
from .models import Order, OrderItem, Address, Cart, CartItem
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string


# Create your views here.

@login_required
def ajax_template_generator(request):
    cart = Cart.objects.get(user=request.user)
    data = render_to_string("AjaxTemplates/cart_template_ajax.html", context={"cart": cart})
    return data


@login_required
def cart_page(request):
    cart = Cart.objects.get(user=request.user)
    return render(request, "cart_app/cart_list.html", context={"cart_list": cart})


@login_required
def cart_add(request, pk):
    if request.method == "POST":
        cart, created = Cart.objects.get_or_create(user=request.user)
        product = get_object_or_404(Product, id=pk)
        color = request.POST.get("color")
        quantity = request.POST.get("quantity", 1)

        if color:
            item, created = CartItem.objects.get_or_create(cart=cart, product=product, color=color)
        else:
            color = product.color.first().title
            item, created = CartItem.objects.get_or_create(cart=cart, product=product, color=color)

        if item:
            item.price = product.discounted_price()
            item.quantity += quantity
            item.save()

        data = ajax_template_generator(request=request)
        return JsonResponse({"data": data, "bool": True})


@login_required
def cart_add_store(request, pk):
    cart, created = Cart.objects.get_or_create(user=request.user)
    product = get_object_or_404(Product, id=pk)
    color = product.color.first().title
    if cart:
        item, created = CartItem.objects.get_or_create(cart=cart, product=product, color=color)
        if item:
            item.price = product.discounted_price()
            item.quantity += 1
            item.save()
            data = ajax_template_generator(request=request)
            return JsonResponse({"data": data, "bool": True})


@login_required
def cart_update(request, pk):
    if request.method == "POST":
        cart_item = get_object_or_404(CartItem, id=pk)
        quantity = request.POST.get("quantity")
        cart_item.quantity = quantity
        cart_item.save()
        data = ajax_template_generator(request=request)
        return JsonResponse({"data": data, "bool": True, "len": cart_item.cart.total_quantity()})


@login_required
def remove_from_cart(request, pk):
    cart_item = get_object_or_404(CartItem, id=pk)
    cart_item.delete()
    data = ajax_template_generator(request=request)
    return JsonResponse({"data": data, "bool": True})


@login_required
def checkout(request):
    cart_list = Cart(request)
    return render(request, "cart_app/checkout.html", context={"cart_list": cart_list})


@login_required
def order_creation(request):
    if request.method == "POST":
        cart = Cart(request)
        f_name = request.POST.get("f_name")
        l_name = request.POST.get("l_name")
        state = request.POST.get("state")
        city = request.POST.get("city")
        address = request.POST.get("address")
        phone = request.POST.get("phone")
        email = request.POST.get("email")
        opn = request.POST.get("optional_note")
        postal_code = request.POST.get("postal_code")
        order_number = random.randint(1000, 10000000)
        print(order_number)
        order = Order.objects.create(user=request.user, total_price=cart.total(), f_name=f_name, l_name=l_name,
                                     phone_number=phone, email=email, state=state, city=city, postal_code=postal_code
                                     , optional_notes=opn, address=address, order_number=order_number)
        for item in cart:
            OrderItem.objects.create(order=order, product=item['product'], color=item['color'],
                                     quantity=item['quantity'], price=item['price'])
            cart.remove_cart()

            return redirect("cart_app:order_detail", order.id)


@login_required
def order_detail(request, pk):
    order = Order.objects.get(id=pk)
    return render(request, "cart_app/order-user-panel.html", context={"order": order})


@login_required
def view_factor(request, pk):
    order = Order.objects.get(id=pk)
    order_items = OrderItem.objects.get(id=order.id)
    return render(request, "cart_app/factor.html", context={"order": order, "product": order_items})


@login_required
def purchases(request):
    return render(request, "cart_app/purchases.html")


@login_required
def address(request):
    addresses = Address.objects.filter(user=request.user)
    if request.method == "POST":
        f_name = request.POST.get("fname")
        l_name = request.POST.get("lname")
        state = request.POST.get("state")
        city = request.POST.get("city")
        address = request.POST.get("address")
        phone = request.POST.get("phone")
        email = request.POST.get("email")
        next_page = request.GET.get("next")
        postal_code = request.POST.get("postal_code")
        Address.objects.create(user=request.user, fname=f_name, lname=l_name, email=email, phone=phone, address=address,
                               city=city, state=state, postal_code=postal_code)
        if next_page:
            return redirect(next_page)
        return render(request, "cart_app/address.html", context={"addresses": addresses})
    return render(request, "cart_app/address.html", context={"addresses": addresses})


@login_required
def edit_address(request, pk):
    address = Address.objects.get(id=pk, user=request.user)
    if request.method == "POST":
        f_name = request.POST.get("fname")
        l_name = request.POST.get("lname")
        state = request.POST.get("state")
        city = request.POST.get("city")
        address = request.POST.get("address")
        phone = request.POST.get("phone")
        email = request.POST.get("email")
        postal_code = request.POST.get("postal_code")
        next_page = request.GET.get("next")
        if f_name:
            x = Address.objects.get(id=pk, user=request.user)
            x.fname = f_name
            x.save()

        if l_name:
            x = Address.objects.get(id=pk, user=request.user)
            x.lname = l_name
            x.save()

        if state:
            x = Address.objects.get(id=pk, user=request.user)
            x.state = state
            x.save()

        if city:
            x = Address.objects.get(id=pk, user=request.user)
            x.city = city
            x.save()

        if address:
            x = Address.objects.get(id=pk, user=request.user)
            x.address = address
            x.save()

        if phone:
            x = Address.objects.get(id=pk, user=request.user)
            x.phone = phone
            x.save()

        if email:
            x = Address.objects.get(id=pk, user=request.user)
            x.fname = f_name
            x.save()

        if postal_code:
            x = Address.objects.get(id=pk, user=request.user)
            x.email = email
            x.save()

        if next_page:
            return redirect(next_page)
        else:
            return redirect("home_app:main")
    return render(request, "cart_app/edit_address.html", context={"address": address})


def test1(request):
    today = datetime.today()
    product = Product.objects.get(id=1)
    j_date = JalaliDate.to_jalali(product.created_at.date())

    # Convert the JalaliDate to a string
    jalali_date_string = j_date.strftime('%Y-%m-%d')

    # Convert the string back to a datetime object
    jalali_date_object = datetime.strptime(jalali_date_string, '%Y-%m-%d')

    # Get the day of the week (Monday is 0 and Sunday is 6)
    day_of_week = jalali_date_object.weekday()

    # Create a list of weekdays as per your requirement
    weekdays = ['4 shanbe', '2 shanbe', '3 shanbe', '4 shanbe', '5 shanbe', 'jomeh', '3 shanbe']

    # Get the actual day of the week from the list
    actual_day = weekdays[day_of_week]

    # Print the result
    return HttpResponse(actual_day)

cart_app/templates/cart_app/address.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <!-- start content -->

    <div class="content">
        <div class="container-fluid">
            <style>
                .line-step-box.complete:nth-child(1):before {
                    width: 100%;
                }
            </style>
        </div>

        <div class="container-fluid">
            <form action="{% url "cart_app:address" %}?next={% url "cart_app:address" %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="check-out-form">
                    <div class="row gy-3">
                        <div class="col-lg-8">
                            <div class="content-box position-sticky top-0">
                                <div class="container-fluid">
                                    <div class="checkout-forms">
                                        <div class="checkout-form-title">
                                            <h5 class="mb-3">ثبت آدرس جدید</h5>
                                        </div>
                                        <div class="checkout-form">

                                            <div class="form-group">
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="name" class="form-label">نام <span
                                                                    class="text-danger ms-1">*</span></label>
                                                            <input type="text" required name="fname" id="name"
                                                                   class="form-control rounded-3">
                                                        </div>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="lname" class="form-label">نام خانوادگی <span
                                                                    class="text-danger ms-1">*</span></label>
                                                            <input type="text" required name="lname" id="lname"
                                                                   class="form-control rounded-3">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="ostan" class="form-label">استان <span
                                                                    class="text-danger ms-1">*</span></label>
                                                            <select id="ostan" name="state"
                                                                    class="form-select rounded-3">
                                                                <option>تهران</option>
                                                                <option>یزد</option>
                                                                <option>اصفهان</option>
                                                                <option>لرستان</option>
                                                                <option>کردستان</option>
                                                            </select>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label for="city" class="form-label">شهر <span
                                                                    class="text-danger ms-1">*</span></label>
                                                            <select id="city" name="city" class="form-select rounded-3">
                                                                <option>کرج</option>
                                                                <option>خرم آباد</option>
                                                                <option>کرمانشاه</option>
                                                                <option>مهاباد</option>
                                                                <option>بروجرد</option>
                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="street" class="form-label">آدرس<span
                                                        class="text-danger ms-1">*</span></label>
                                                <textarea type="text" required name="address"
                                                          placeholder="پلاک خانه و نام خیابان"
                                                          id="street"
                                                          class="form-control rounded-3"></textarea>
                                            </div>
                                            <div class="form-group">
                                                <label for="tel" class="form-label">تلفن<span
                                                        class="text-danger ms-1">*</span></label>
                                                <input type="text" required name="phone" id="tel"
                                                       class="form-control rounded-3">
                                            </div>
                                            <div class="form-group">
                                                <label for="email" class="form-label">آدرس ایمیل<span
                                                        class="text-danger ms-1"></span></label>
                                                <input type="text" name="email" id="email"
                                                       class="form-control rounded-3">
                                            </div>
                                            <div class="form-group">
                                                <label for="postal-code" class="form-label">کد پستی<span
                                                        class="text-danger ms-1">*</span></label>
                                                <input type="text" required name="postal_code" id="postal-code"
                                                       class="form-control rounded-3">
                                            </div>
                                            <div class="action mt-3 d-flex align-items-center justify-content-center">
                                                <button type="submit"
                                                        class="btn border-0 main-color-two-bg rounded-3 py-2 d-block w-100">
                                                    ثبت
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="checkout-side position-sticky top-0">
                                <div class="cart-canvases mb-4">
                                    <div class="item">
                                        <div class="factor">
                                            <div class="title">
                                                <div class="d-flex align-items-end">
                                                    <i class="bi bi-rocket-fill me-2 main-color-one-color"></i>
                                                    <h6 class="font-16">لیست آدرس ها
                                                    </h6>
                                                </div>
                                            </div>
                                            <div class="row gy-2">
                                                {% for address in addresses %}
                                                        <div class="col-12">
                                                            <div class="shipping-item">
                                                                <h6 class="font-14 mx-2">آدرس {{ forloop.counter }}
                                                                    :</h6>
                                                                <p class="mb-0 text-muted">{{ address.address }}</p>
                                                                &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                                                                <a href="{% url "cart_app:edit_address" address.id %}"
                                                                   class="text-primary">ویرایش</a>
                                                            </div>
                                                        </div>
                                                {% empty %}
                                                    شما آدرسی ندارید
                                                    <a style="font-weight: bold; color: #0d6efd;"
                                                       onclick="change_loc()">اضافه کنید!
                                                    </a>
                                                {% endfor %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <script>
        function change_loc() {
            window.location.href = "#name"
        }
    </script>
{% endblock %}

cart_app/templates/cart_app/order-user-panel.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="content">
        <div class="container-fluid">

            <style>
                .line-step-box.complete:nth-child(1):before {
                    width: 100%;
                }
            </style>

            <div class="line-step-container d-sm-block d-none">
                <div class="line-step">
                    <div class="line-step-boxs">
                        <div class="line-step-box complete">
                            <a href="{% url "cart_app:cart_list" %}">
                                <p>سبد خرید</p>
                                <div class="icon">
                                    1
                                </div>
                            </a>
                        </div>
                        <div class="line-step-box complete">
                            <a href="{% url "cart_app:checkout" %}">
                                <p>جزییات پرداخت</p>
                                <div class="icon">
                                    2
                                </div>
                            </a>
                        </div>
                        <div class="line-step-box disabled">
                            <a href="cart.html">
                                <p>تکمیل سفارش</p>
                                <div class="icon">
                                    3
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="container-fluid">
            <div class="dashboard-panel">
                <div class="row gy-3">
                    <div class="col-lg-9">
                        <div class="content-box">
                            <div class="container-fluid">
                                <div class="title-panel">
                                    <h6 class="font-16">
                                        سفارشات
                                    </h6>
                                </div>
                                <div class="responsive-table p-0">
                                    <table class="table main-table rounded-0">
                                        <thead class="text-bg-dark bg-opacity-75 text-center">
                                        <tr>
                                            <th>#</th>
                                            <th>شماره سفارش</th>
                                            <th>تاریخ ثبت سفارش</th>
                                            <th>مبلغ پرداختی</th>
                                            <th>وضعیت سفارش</th>
                                            <th>جزییات</th>
                                        </tr>
                                        </thead>
                                        <tbody class="text-center">
                                        <tr>
                                            <td class="font-14">1</td>
                                            <td class="font-14">{{ order.order_number }}</td>
                                            <td class="font-14">{{ order.created_at }}</td>
                                            <td class="font-14">{{ order.total_price }} تومان</td>
                                            <td class="font-14"><span class="success-label rounded-pill">سفارش در حال ارسال</span>
                                            </td>
                                            <td class="font-14">
                                                <a href="{% url "cart_app:factor_page" order.id %}"
                                                   class="btn btn-sm border-0 main-color-one-bg waves-effect waves-light">مشاهده
                                                    <i
                                                            class="bi bi-chevron-left text-white font-16"></i></a>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

cart_app/templates/cart_app/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="">

</form>
</body>
</html>