EcommerceWebsite_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("account_app.urls")),
    path("", include("home_app.urls")),
    path("products/", include("product_app.urls")),
    path("cart/", include("cart_app.urls")),
    path("blog/", include("weblog_app.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart_app/urls.py
from django.urls import path
from . import views

app_name = "cart_app"
urlpatterns = [
    path("cart_add/<int:pk>/", views.cart_add, name="add"),
    path("cart_add_store/<int:pk>/", views.cart_add_store, name="cart_add_store"),
    path("remove_from_cart/<int:pk>/", views.remove_from_cart, name="remove_cart"),
    path("cart_list", views.cart_page, name="cart_list"),
    path("cart_update/<int:pk>", views.cart_update, name="cart_update"),
    path("checkout", views.checkout, name="checkout"),
    path("order_creation", views.order_creation, name="order_creation"),
    path("order_detail/<int:pk>", views.order_detail, name="order_detail"),
    path("factor_page/<int:pk>", views.view_factor, name="factor_page"),
    path("purchases", views.purchases, name="purchases"),
    path("address", views.address, name="address"),
    path("edit_address/<int:pk>", views.edit_address, name="edit_address"),
    path("test", views.test1),
]

weblog_app/urls.py
from . import views
from django.urls import path


app_name = "weblog_app"
urlpatterns = [
    path("detail/<str:slug>", views.blog_detail, name="detail_blog"),
    path("", views.blog, name="blog"),
    path("blog_comment/<int:pk>", views.blog_comment, name="blog_comments"),
    path("blog_list", views.blog_list, name="blog_list"),
    path("blog_search", views.search_blogs, name="blog_search"),
    path("blog_filter", views.blog_filter, name="blog_filter"),
    path("blog_video/<str:slug>", views.blog_detail_video, name="blog_detail_video"),
    path("video_comment/<int:pk>", views.blog_video_comment, name="blog_video_comment"),
]

weblog_app/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.utils.text import slugify
from persiantools.jdatetime import JalaliDate
from account_app.models import User
from taggit.managers import TaggableManager


# Create your models here.

class WeblogCategroy(models.Model):
    title = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class IpModel(models.Model):
    ip = models.CharField(max_length=100)

    def __str__(self):
        return self.ip


class Weblog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="weblog")
    main_title = models.CharField(max_length=50, null=True, blank=True, unique=True)
    main_image = models.ImageField(upload_to="img/blog-pics", null=True, blank=True)
    content = RichTextUploadingField(null=True, blank=True)
    category = models.ManyToManyField(WeblogCategroy, related_name="categories")
    created_at = models.DateTimeField(auto_now_add=True)
    study_time = models.IntegerField(default=5)
    tags = TaggableManager()
    views = models.IntegerField(default=0)
    slug = models.SlugField(unique=True, null=True, blank=True, allow_unicode=True)
    ip = models.ManyToManyField(IpModel, related_name="post_views")

    def __str__(self):
        return self.main_title

    def save(
            self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        self.slug = slugify(self.main_title, allow_unicode=True)
        self.views = self.ip.count()
        super(Weblog, self).save()

    def created_at_jdate(self):
        date = self.created_at.date()
        jdate = JalaliDate.to_jalali(date)
        persian_months = ["فروردین", "اردیبهشت", "خرداد", "تیر", "مرداد", "شهریور", "مهر", "آبان", "آذر", "دی", "بهمن",
                          "اسفند"]
        return f"{jdate.day} / {persian_months[jdate.month - 1]} / {jdate.year}"

    @property
    def total_views(self):
        return self.ip.count()


class WeblogVideo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="weblog_video")
    main_title = models.CharField(max_length=50)
    thumbnail = models.ImageField(upload_to="img/thumbnails", null=True, blank=True)
    category = models.ManyToManyField(WeblogCategroy, related_name="video_categories")
    description = models.TextField()  # description
    video = models.FileField(upload_to="weblog-video/")
    slug = models.SlugField(null=True, blank=True, allow_unicode=True, unique=True)
    study_time = models.IntegerField(default=5)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.main_title

    def save(
            self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        self.slug = slugify(self.main_title, allow_unicode=True)

        super(WeblogVideo, self).save()


class WeblogComment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="blog_comments")
    blog = models.ForeignKey(Weblog, on_delete=models.CASCADE, related_name="blog_comments")
    parent = models.ForeignKey("self", on_delete=models.CASCADE, related_name="replies", null=True, blank=True)
    body = models.TextField(default="None")
    email = models.EmailField()
    name = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.author} - {self.blog.main_title}"


class WeblogVideoComment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="blog_video_comments")
    blog = models.ForeignKey(WeblogVideo, on_delete=models.CASCADE, related_name="blog_video_comments")
    parent = models.ForeignKey("self", on_delete=models.CASCADE, related_name="replies", null=True, blank=True)
    body = models.TextField(default="None")
    email = models.EmailField()
    name = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.author} - {self.blog.main_title}"

weblog_app/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from weblog_app.models import Weblog, WeblogComment, WeblogCategroy, IpModel, WeblogVideo, WeblogVideoComment


# Create your views here.
def blog(request):
    categories = WeblogCategroy.objects.all()
    popular_blogs = Weblog.objects.all().order_by("views")[:8]
    new_videos = WeblogVideo.objects.all().order_by("-created_at")[:8]
    latest = Weblog.objects.all().order_by("-created_at")[:8]
    return render(request, "weblog_app/blog.html", context={"categories": categories, "new_videos": new_videos, "latest"
    : latest, "popular_blogs": popular_blogs})


def blog_list(request):
    sort = request.GET.get("sort")
    blogs = Weblog.objects.all()
    if sort:
        if sort == "popular":
            # blogs = sorted(Weblog.objects.all(), key=lambda x: x.total_views())
            blogs = Weblog.objects.all().order_by("views").distinct()
        elif sort == "videos":
            blogs = WeblogVideo.objects.all().order_by("-created_at").distinct()
            print("hi 5 ")
        elif sort == "latest":
            blogs = Weblog.objects.all().order_by("-created_at").distinct()

    categories = WeblogCategroy.objects.all()
    page_number = request.GET.get("page")

    paginator = Paginator(blogs, 4)
    object_list = paginator.get_page(page_number)

    return render(request, "weblog_app/blog_list.html", context={"blogs": object_list, "categories": categories})


def get_ip(request):
    address = request.META.get('HTTP_X_FORWARDED_FOR')
    if address:
        ip = address.split(",")[-1].strip()
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def search_blogs(request):
    q = request.GET.get("search_blog")
    blogs = Weblog.objects.filter(main_title__icontains=q)
    categories = WeblogCategroy.objects.all()

    return render(request, "weblog_app/blog_list.html", context={"blogs": blogs, "categories": categories})


def blog_filter(request):
    categories1 = request.GET.getlist("category")
    page_number = request.GET.get("page")
    categories = WeblogCategroy.objects.all()
    blogs = Weblog.objects.filter(category__title__in=categories1)

    paginator = Paginator(blogs, 4)
    object_list = paginator.get_page(page_number)

    return render(request, "weblog_app/blog_list.html", context={"blogs": object_list, "categories": categories})


def blog_detail(request, slug):
    blog = Weblog.objects.get(slug=slug)
    related_blogs = Weblog.objects.filter(category__in=blog.category.all()).distinct()[:5]
    ip = get_ip(request)
    print(ip)
    if IpModel.objects.filter(ip=ip).exists():
        print("ip already exists")
        post = Weblog.objects.get(slug=slug)
        post.ip.add(IpModel.objects.get(ip=ip))
    else:
        IpModel.objects.create(ip=ip)
        post = Weblog.objects.get(slug=slug)
        post.ip.add(IpModel.objects.get(ip=ip))
    return render(request, "weblog_app/blog_detail.html", context={"blog": blog, "rb": related_blogs})


def blog_detail_video(request, slug):
    blog = WeblogVideo.objects.get(slug=slug)
    rb = WeblogVideo.objects.filter(category__in=blog.category.all())
    return render(request, "weblog_app/blog_detail_video.html", context={"blog": blog, "rb": rb})


def blog_comment(request, pk):
    if request.method == "POST":
        name = request.POST.get("name")
        body = request.POST.get("body")
        email = request.user.email
        parent_id = request.POST.get("parent_id")
        blog = Weblog.objects.get(id=pk)
        if parent_id:
            comment = WeblogComment.objects.create(name=name, body=body, email=email, author=request.user,
                                                   parent_id=parent_id, blog=blog)
        else:
            comment = WeblogComment.objects.create(name=name, body=body, email=email, author=request.user, blog=blog)
        return redirect("weblog_app:detail_blog", blog.slug)


def blog_video_comment(request, pk):
    if request.method == "POST":
        print(pk)
        name = request.POST.get("name")
        body = request.POST.get("body")
        email = request.user.email
        parent_id = request.POST.get("parent_id")
        blog = WeblogVideo.objects.get(id=pk)
        if parent_id:
            WeblogVideoComment.objects.create(name=name, body=body, email=email, author=request.user,
                                              parent_id=parent_id, blog=blog)
        else:
            WeblogVideoComment.objects.create(name=name, body=body, email=email, author=request.user,
                                              blog=blog)
        return redirect("weblog_app:blog_detail_video", blog.slug)

weblog_app/templates/weblog_app/blog_list.html
{% extends 'base.html' %}
{% load static %}
{% load templatetags %}

{% block content %}
    <div class="content">
        <div class="container-fluid">
            <div class="content-box">
                <div class="container-filter-boxes">
                    <div class="container-fluid1">
                        {% for blog in blogs %}
                            <a href="{% url "weblog_app:detail_blog" blog.slug %}?id={{ blog.id }}">
                                <div class="box">
                                    {% if blog.main_image %}
                                        <img src="{{ blog.main_image.url }}" class="img-box"/>
                                    {% else %}
                                        <img src="{% static "image/blog_pic.jpg" %}" class="img-box"/>
                                    {% endif %}
                                    <input type="hidden" name="post-id" value="{{ blog.id }}">
                                    <h6>{{ blog.main_title }}</h6>
                                    <p>{{ blog.total_views }} views</p>
                                    <div class="container-admin">
                                        {% if blog.author.prof_pic %}
                                            <img class="rounded-circle" src="{{ blog.author.prof_pic.url }}"/>
                                        {% else %}
                                            <img src="{% static "image/user.png" %}"/>
                                        {% endif %}
                                        <p>{{ blog.author.full_name }}</p>
                                    </div>
                                </div>
                            </a>
                        {% endfor %}
                    </div>
                    <div class="filter-conet">
                        <div class="filter-items position-sticky top-0">
                            <div class="container-fluid">
                                <div class="filter-item">
                                    <h5 class="filter-item-title">جستجو</h5>
                                    <div class="filter-item-content">
                                        <div class="search-form">
                                            <form action="{% url "weblog_app:blog_search" %}">
                                                <div class="search-filed">
                                                    <input name="search_blog" type="text"
                                                           placeholder="جستجوی محصولات ..."
                                                           class="form-control search-input">
                                                    <button type="submit"
                                                            class="btn search-btn main-color-one-bg rounded-pill"><i
                                                            class="bi bi-search"></i></button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <form action="{% url "weblog_app:blog_filter" %}" method="GET">
                                    <div class="filter-item">
                                        <h5 class="filter-item-title">دسته بندی ها</h5>
                                        <div class="filter-item-content">

                                            {% for category in categories %}
                                                <div class="d-flex align-items-center justify-content-between flex-wrap mb-3">
                                                    <div class="form-check">
                                                        <label for="{{ category.id }}"
                                                               class="form-check-label">{{ category.title }}<i
                                                                class="bi bi-phone me-1"></i></label>
                                                        <input type="checkbox" value="{{ category.title }}"
                                                               name="category"
                                                               id="{{ category.id }}"
                                                               class="form-check-input">
                                                    </div>
                                                    <div>
                                                        <span class="fw-bold font-14">({{ category.title|blog_category_len }})</span>
                                                    </div>
                                                </div>
                                            {% endfor %}

                                        </div>
                                    </div>
                                    <div class="filter-item text-center">
                                        <button type="submit" class="btn-outline-site">اعمال فیلتر</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                {% if blogs.has_other_pages %}
                    <div class="col-12">
                    <div class="my-paginate my-4">
                    <nav aria-label="Page navigation example">
                    <ul class="pagination flex-wrap justify-content-center">
                    {% if blogs.has_previous %}
                        <li class="page-item">
                            <a class="page-link rounded-3"
                               href="{% url "weblog_app:blog_list" %}?page=
                                       {{ blogs.previous_page_number }}{% if request.GET.search_blog %}?search_blog={{ request.GET.search_blog }}{% endif %}{% if request.GET.category %}{% for cat in request.GET|get_list:"category" %}&category={{ cat }}{% endfor %}{% endif %}">قبلی</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link rounded-3" href="#">قبلی</a>
                        </li>
                    {% endif %}
                    {% for x in blogs.paginator.page_range %}
                        {% if blogs.number == x %}
                            <li class="page-item active"><a class="page-link rounded-3"
                                                            href="{% url "weblog_app:blog_list" %}?page=
                                                                    {{ x }}{% if request.GET.search_blog %}?search_blog={{ request.GET.search_blog }}{% endif %}{% if request.GET.category %}{% for cat in request.GET|get_list:"category" %}&category={{ cat }}{% endfor %}{% endif %}">{{ x }}</a>
                            </li>
                        {% elif x > blogs.number|add:'-4' and x < blogs.number|add:'4' %}
                            <li class="page-item"><a class="page-link rounded-3"
                                                     href="{% url "weblog_app:blog_list" %}?page=
                                                             {{ x }}{% if request.GET.search_blog %}?search_blog={{ request.GET.search_blog }}{% endif %}{% if request.GET.category %}{% for cat in request.GET|get_list:"category" %}&category={{ cat }}{% endfor %}{% endif %}">{{ x }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if blogs.has_next %}
                        {% if blogs.number < blogs.paginator.num_pages|add:'-2' %}
                            <li class="page-item active"><a class="page-link rounded-3"
                                                            href="{% url "weblog_app:blog_list" %}?page=
                                                                    {{ blogs.next_page_number }}{% if request.GET.search_blog %}?search_blog={{ request.GET.search_blog }}{% endif %}{% if request.GET.category %}{% for cat in request.GET|get_list:"category" %}&category={{ cat }}{% endfor %}{% endif %}">بعدی</a>
                            </li>
                        {% elif blogs.number < blogs.paginator.num_pages|add:'-3' %}
                            <li class="page-item active"><a class="page-link rounded-3"
                                                            href="{% url "weblog_app:blog_list" %}?page=
                                                                    {{ blogs.next_page_number }}{% if request.GET.search_blog %}?search_blog={{ request.GET.search_blog }}{% endif %}{% if request.GET.category %}{% for cat in request.GET|get_list:"category" %}&category={{ cat }}{% endfor %}{% endif %}">بعدی</a>
                            </li>
                        {% else %}
                            <li class="page-item active"><a class="page-link rounded-3"
                                                            href="{% url "weblog_app:blog_list" %}?page=
                                                                    {{ blogs.next_page_number }}{% if request.GET.search_blog %}?search_blog={{ request.GET.search_blog }}{% endif %}{% if request.GET.category %}{% for cat in request.GET|get_list:"category" %}&category={{ cat }}{% endfor %}{% endif %}">بعدی</a>
                            </li>
                        {% endif %}
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link rounded-3" href="#">بعدی</a>
                        </li>
                    {% endif %}
                {% endif %}
                </ul>
                </nav>
                </div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}